### ISSUE TITLE
sprite de Cartas 

### ISSUE THREAD

**Issue by Villanuevand** [jorgeucano/RunoX#1]
Voy a hacer el sprite de cartas de unos usando esta imagen. 

![uno-sprite-original](https://user-images.githubusercontent.com/1209238/77585098-b2298e00-6ec2-11ea-944e-56b4e2918408.png)

Pendiente de revision en #3

**Comment by facurodriguez** [comment]
@jorgeucano este issue ya podría cerrarse ya que #3 ya se aprobó
