### ISSUE TITLE
No funciona el botón RUNOX. 

### ISSUE THREAD

**Issue by juanmab** [jorgeucano/RunoX#114]
Imposible ganar :(

**Comment by jorgeucano** [comment]
@facurodriguez sera el cambio en el engine ? Hoy lo fixeamos @juanmab

**Comment by facurodriguez** [comment]
Hay un PR abierto que lo fixea

**Comment by jorgeucano** [comment]
fixed

**Comment by juanmab** [comment]
@jorgeucano sigue sucediendo el problema

**Comment by jorgeucano** [comment]
Lo REFIXEAMOS EN VIVO Y YA funciona hermosamente!
