### ISSUE TITLE
ERROR "La carta ya esta dibujada en la cima del stack"

### ISSUE THREAD

**Issue by AlexScigalszky** [jorgeucano/RunoX#118]
No se puede avanzar en el juego
![imagen](https://user-images.githubusercontent.com/20727215/85204521-7a788980-b2eb-11ea-871b-71d604d91cff.png)

Pero si selecciono una carta (en este caso el 9 amarillo) dispara ese log pero no permite avanzar (también cambia de turno pero pasa lo mismo para el otro jugador sin importar lo que tire)

**Comment by jorgeucano** [comment]
fixed
