### ISSUE TITLE
from wireframe to html y css

### ISSUE THREAD

**Issue by jorgeucano** [jorgeucano/RunoX#27]
Tenemos que dividir esto y crear el css de cada cosa

![image](https://user-images.githubusercontent.com/5982204/79270360-68eead80-7e74-11ea-90db-be9be5a77a48.png)

https://twitter.com/_webbegg/status/1250140204242960384/

**Comment by webbegg** [comment]
# Wireframes (hires) 

Añadimos los wireframes de las pantallas de:

- **Login** La de registro sería igual pero con doble campo contraseña para su validación.
- **Salones de Juego**. Donde los usuarios deciden si quieren unirse una sala creada o prefieren crear una ellos mismos. El formulario hay que adaptarlo a las opciones que decidamos. Tal vez en un futuro podríamos añadir modos de juego (como un time-limit) o temas para las salas de juego cambiando fondo o similar. En un futuro podríamos mostrar una especie de SCORE del usuario. 
- **Pantalla de juego** Aquí transcurre la partida y es la que más funcionalidades muestra, prepararé un documento explicando las distintas partes y con que propósito/funcionalidad se pensaron.

> ⚠️ Los diseños de guía para la maquetación de las páginas, los he preparado teniendo en cuenta proyectos anteriores y la mayoría de la funcionalidad debería de ser viable, pero ya iremos valorando entre todos que implementamos y que no.

> ⚠️ Ni que decir tiene que absolutamente todas las criticas constructivas o dudas que tengáis sobre los diseños, serán mas que bienvenidas.
 
![1  LOGIN:REGISTER](https://user-images.githubusercontent.com/334047/79597100-fd117c80-80e1-11ea-9cca-d8ab0746b358.jpg)
![2  SALONES](https://user-images.githubusercontent.com/334047/79597112-013d9a00-80e2-11ea-9122-1aad3402f147.jpg)
![3  PARTIDA](https://user-images.githubusercontent.com/334047/79597115-01d63080-80e2-11ea-8fd5-5a75a20a146d.jpg)
