### ISSUE TITLE
pasar lo que existe a tailwind

### ISSUE THREAD

**Issue by jorgeucano** [jorgeucano/RunoX#28]

**Comment by webbegg** [comment]
Al tratarse esta de la versión vanilla y no disponer de templates html como tal, se complica un poco estilar directamente con las clases de Tailwindcss. La UI dispone de estilos bastantes personalizados y algunos muy concretos. De momento deberíamos maquetar con css plano y cuando vayamos fijando las pantallas, vemos la viabilidad de aplicarle las clases de Tailwind.
