### ISSUE TITLE
Al jugar la carta +2 solo permite jugar una carta +2 en el siguiente turno.

### ISSUE THREAD

**Issue by ernestocardenas79** [jorgeucano/RunoX#43]
Al jugar la carta +2 solo permite jugar una carta +2 en el siguiente turno, aparte debería permitir jugar cualquier carta del mismo color.

**Comment by facurodriguez** [comment]
@ernestocardenas79 - en #44 se corrigió el comportamiento del +2.

Con respecto a jugar otra carta, las [reglas oficiales del uno](http://www.uno-juego.es/reglas-del-juego/) indican que:

> el siguiente jugador debe tomar dos cartas y no puede deponer ninguna carta en esta ronda

Lo que nosotros hicimos fue utilizar una "regla de la casa" que es permitir que el siguiente jugador, de tener un +2 en su mano, pueda jugarlo.

**Comment by ernestocardenas79** [comment]
Mas que claro..... fantástico trabajo

saludos
