### ISSUE TITLE
Separar la logica del juego en un paquete npm

### ISSUE THREAD

**Issue by facurodriguez** [jorgeucano/RunoX#55]
La idea es poder transporta nuestra logica del juego entre distintos tipos de proyectos.

Para lograr esto la idea es separar todo lo relacionado el motor del juego a un paquete npm.

Los elementos que deberían estar en el paquete son:
- src/commands
- src/events
- src/models
- src/utils
- src/game-engine.ts

**Comment by jorgeucano** [comment]
esto se tiene que mover a Game engine---- y lo vamos a implementar en node
